### ISSUE TITLE
Fields added with AddFields transformations in builder manifests are downcased

### ISSUE THREAD

**Issue by jscheel** [airbytehq/PyAirbyte#576]
I have a transformation that adds a field. When I sync, the field does get added, but it is downcased. This does not happen on the airbyte test interface.

```
transformations:
    - type: AddFields
      fields:
        - path:
            - conversationId
          value: "{{stream_partition.conversationId}}"
```

The field is added, but it is added as `conversationid` instead of `conversationId`
